# Generated by Django 5.2.5 on 2025-09-12 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
        ("tuition", "0003_remove_assignment_tuition_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="progress",
            unique_together={("student", "tuition")},
        ),
    ]
