# Generated by Django 5.2.5 on 2025-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="institution",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
