# Generated by Django 5.2.5 on 2025-09-10 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tuition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="progress",
            name="assignments_completed",
            field=models.ManyToManyField(blank=True, to="tuition.assignment"),
        ),
        migrations.AddField(
            model_name="progress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="progress",
            name="completed_topics",
            field=models.ManyToManyField(blank=True, to="tuition.topic"),
        ),
        migrations.AddField(
            model_name="tuition",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="tuition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="tuition.tuition",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="tuition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="tuition.tuition",
            ),
        ),
        migrations.AddField(
            model_name="progress",
            name="tuition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_progress",
                to="tuition.tuition",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="tuition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="tuition.tuition",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="tuition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="tuition.tuition",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "tuition")},
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("user", "tuition")},
        ),
    ]
