# Generated by Django 5.2.5 on 2025-09-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tuition", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="tuition",
        ),
        migrations.RemoveField(
            model_name="progress",
            name="assignments_completed",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payer",
        ),
        migrations.RemoveField(
            model_name="progress",
            name="completed_topics",
        ),
        migrations.RemoveField(
            model_name="progress",
            name="student",
        ),
        migrations.RemoveField(
            model_name="progress",
            name="tuition",
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="review",
            name="tuition",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="tuition",
        ),
        migrations.DeleteModel(
            name="Application",
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Progress",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
